// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_PD_XtX8xsvgHMPSw3uxN1M5xbjqpcd8',
    appId: '1:894280733558:web:7e6432ded60e3829726057',
    messagingSenderId: '894280733558',
    projectId: 'certon-ccf37',
    authDomain: 'certon-ccf37.firebaseapp.com',
    databaseURL: 'https://certon-ccf37.firebaseio.com',
    storageBucket: 'certon-ccf37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIwe7RRu4Cge5i_oYea5UO6MF5c68rkdo',
    appId: '1:894280733558:android:3da3ed325ed86c00',
    messagingSenderId: '894280733558',
    projectId: 'certon-ccf37',
    databaseURL: 'https://certon-ccf37.firebaseio.com',
    storageBucket: 'certon-ccf37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Bec9V0wPZeETmwhTzdSV49r2yVDNkFk',
    appId: '1:894280733558:ios:87b5eae3ece4b296726057',
    messagingSenderId: '894280733558',
    projectId: 'certon-ccf37',
    databaseURL: 'https://certon-ccf37.firebaseio.com',
    storageBucket: 'certon-ccf37.appspot.com',
    iosClientId:
        '894280733558-3r8g9jhc9mi7smvvlb8d13vgtn6uglld.apps.googleusercontent.com',
    iosBundleId: 'com.certonhublandlord.app',
  );
}
